name: Django Tests

on:
  push:
    branches:
      - main
      - ahmed
  pull_request:
    branches:
      - main
      - ahmed

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ah@223500
          POSTGRES_DB: my_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django pytest pytest-django psycopg2-binary Pillow
       

    - name: Run migrations
      env:
        DATABASE_URL: postgres://postgres:postgres@postgres:5432/my_database
      run: |
        cd Django-Online_shop1/
        pip install sorl-thumbnail
        # pip install suds
        # pip install zeep
        # pip install suds-jurko
        # python manage.py makemigrations
        python manage.py migrate

    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:postgres@postgres:5432/my_database
      run: |
        cd Django-Online_shop1/
        python manage.py test
