name: Django Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db

    env:
      DJANGO_SETTINGS_MODULE: your_project.settings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'


      # Step 3: Run migrations
      - name: Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      # Step 4: Run tests
      - name: Run tests
        run: python manage.py test
